In [2]:
import numpy as np

print(np.__version__)


1.26.4


In [8]:
arr = np.array([1,2,3])
print(arr)
print(arr.shape)
print(arr.size)
print(arr.ndim)
print(arr.dtype)
print(arr[1])


[1 2 3]
(3,)
3
1
int64
2


In [12]:
arr = np.array([
    [1,2,3],
    [4,5,6]
    ])
print(arr)
print(arr.shape)
print(arr.size)
print(arr.ndim)
print(arr.dtype)
print(arr[0][2])


[[1 2 3]
 [4 5 6]]
(2, 3)
6
2
int64
3


In [17]:
arr = np.arange(1,11,3)
print(arr)

[ 1  4  7 10]


In [20]:
arr = np.zeros([2,3,4])
print(arr)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [21]:
arr = np.ones([2,3])
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [36]:
arr = np.random.randint(0,100,(100,100))
print(arr)

[[ 8 46  0 ... 64  7 60]
 [75 83 78 ... 20 50 79]
 [87 26 16 ...  3 18 80]
 ...
 [28 79  9 ... 99 88 50]
 [54 31 92 ... 75 94 85]
 [58 21 85 ... 92 13 31]]


In [39]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [42]:
arr = np.arange(1,10)
arr = arr.reshape((3,3))
print(arr)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [47]:
arr = np.array([
    [1,2,3],
    [4,5,6]])
print(arr)
print(arr.shape)

arr = arr.transpose()
print(arr)
print(arr.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[1 4]
 [2 5]
 [3 6]]
(3, 2)


In [49]:
arr1 = np.array([[1, 2, 3, 4]])
arr2 = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
    ])
arr = np.concatenate((arr2, arr1))
print(arr)

[[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]]


In [56]:
arr = np.arange(0,8).reshape(2,4)
print(arr)
arr1, arr2 = np.split(arr,2, axis=1)
print(arr1, arr2)


[[0 1 2 3]
 [4 5 6 7]]
[[0 1]
 [4 5]] [[2 3]
 [6 7]]
